- handler.go
- network.go
Add collection of local ip addresses
> Report ip addresses

- cmd/cagent/main.go
- config.go
> -p flag to dump active config to output

- processes.go
- processes_notwindows.go
- processes_windows.go
See DEV-427:
...
Include the parent pid of each process.
```
{
"PID": 24,
"Name": "oom_reaper",
"State": "sleeping",
"Cmdline": "",
"parent_PID": 0
}
```
> PROC: add parent_PID

- processes_notwindows.go
> PROC: make errors more clear

- pkg-scripts/msi-templates/WixUI_HK.wxs
- pkg-scripts/msi-templates/product.wxs
In order to make MSI upgrade works for `-rc` versions
> MSI: allow installl for the same version

- .circleci/config.yml
> fix typo in filename x68 -> x86

- .circleci/config.yml
- .golangci.yml
List of enabled linters:
- goimports
- golint
- gosimple
- structcheck
- deadcode
- staticcheck
- errcheck
- unused
- gosec
- dupl
- gocyclo
- misspell
- unparam
> Configure golangci

- cpu.go
- processes_windows.go
- system.go
See DEV-495
- Sort results of cores on Windows to provide the consistent index of CPU
- Clarify some timeouts constants
> Cpu win fixes

- cmd/cagent/main.go
see DEV-486
- Note that cagent service is running
- Do not mention how to start
Next, we will need to add the HUB_URL check on install to ensure firewall doesn't block outgoing connection
> Service install, make console msg more clear

- build-win.bat
Fix path for windows so signtool can find the certificate used for signing
> use proper windows paths

- cagent.go
- cmd/cagent/main.go
Small refactoring as discussed in Slack
> remove SetVersion and pass version as argument to New

- vendor/github.com/go-ole/go-ole/safearray_windows.go
- vendor/github.com/go-ole/go-ole/safearrayconversion.go
It fixes issue https://github.com/go-ole/go-ole/issues/172
Signed-off-by: Artur Troian <troian.ap@gmail.com>
> Cherry-pick of https://github.com/go-ole/go-ole/pull/180

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/go-ole/go-ole/README.md
- vendor/github.com/go-ole/go-ole/com.go
- vendor/github.com/go-ole/go-ole/com_func.go
- vendor/github.com/go-ole/go-ole/idispatch_windows.go
- vendor/github.com/go-ole/go-ole/safearray_func.go
- vendor/github.com/go-ole/go-ole/variant.go
- vendor/github.com/go-ole/go-ole/variant_date_386.go
- vendor/github.com/go-ole/go-ole/variant_date_amd64.go
- vendor/github.com/go-ole/go-ole/variant_ppc64le.go
Update from official repo which includes fix of https://github.com/cloudradar-monitoring/cagent/pull/45
> update go-ole to v1.2.2

- .circleci/config.yml
- build-win.bat
> migrate to new signing machine

- cagent.go
- config.go
- handler.go
- mem_windows.go
- perfcounters/win_perf_counters.go
- pkg/monitoring/top/top.go
- pkg/monitoring/top/top_nonwindows.go
- pkg/monitoring/top/top_windows.go
- pkg/monitoring/vmstat/hyperv/hyperv_wmi.go
- pkg/monitoring/vmstat/hyperv/provider_windows.go
- pkg/monitoring/vmstat/onbuild_dependency/windows.go
- pkg/monitoring/vmstat/vmstat.go
- pkg/monitoring/watcher_windows.go
- pkg/wmi/wmi.go
- virt_nonwindows.go
- virt_windows.go
Include list of running Hyper-V VMs.
Output includes `virt.hyper-v` entry with with list of VMs
> List hyperv vms

- .circleci/config.yml
- pkg-scripts/msi-templates/FolderUninstall.wxs
- pkg-scripts/msi-templates/product.wxs
- fix MSI building by adding the resource folder (broke with bad rebase)
- test hook was run before updating env vars
- config/log remove on install was broken (still broken if using control center to remove the app)
> Some MSI fixes

- cmd/cagent/toast_windows.go
Toast duration was 'short' by default, according to measurements, it is approx 5sec.
Now I set it to 'long' and it stays for 25sec
> win: make the toasts appear longer

- cmd/cagent/main.go
- handler.go
- pkg/monitoring/services/services.go
- pkg/monitoring/services/services_windows.go
Available service managers:
- Systemd
- SysvInit
- Upstart
- Windows Service Manager
> Parse services list on linux&windows

- .circleci/config.yml
- .gitignore
- Makefile
See: https://github.com/golangci/golangci-lint#install
> Add Makefile extract some ci tasks to it and bump build image

- cmd/cagent/main.go
- pkg-scripts/preremove.sh
- try to stop only running service
- dep/rpm: do not stop pkg remove on service uninstall error
> Improve service uninstall flow

- cmd/cagent/main.go
- cmd/cagent/toast_windows.go
- cmd/cagent/winui.go
- cmd/cagent/winui_fallback.go
- pkg-scripts/msi-templates/WixUI_HK.wxs
- pkg-scripts/msi-templates/product.wxs
- wix.json
- check for admin rights
- run UI after msi install
> improve win UI and msi install

- raid.go
> do not generate results error on missing /proc/mdstat

- cagent.go
- handler.go
- pkg/monitoring/top/top.go
All the issues we will find during integration
> WIP: More top fixes for process monitoring

- wix.json
it will close the UI after successful test&save
> MSI: Use cagent:install hook instead of cagent:settings

- pkg/monitoring/services/services_windows.go
WMI returns nil Description for some services
> Windows WMI fix: make Description *string

- cagent.go
- config.go
- cpu.go
- cpu_utilisation_analyser.go
- example.config.toml
- handler.go
- monitor CPU util metrics using new ThresholdNotifier at CPU Watcher
- Start/Stop Top measurement when it exceed
- Sort, cut and provide top results
> CPU threshold notifier & top integration

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/cloudradar-monitoring/dmidecode/LICENSE
- vendor/github.com/cloudradar-monitoring/dmidecode/dmidecode.go
- vendor/github.com/cloudradar-monitoring/dmidecode/types.go
Fixes empty Characteristics array provided by `dmidecode` tool on some machines
> dep: update dmidecode to 0.0.3

- cmd/cagent/winui.go
- handler.go
- pkg-scripts/msi-templates/product.wxs
see DEV-682 comments
- make the separate method `TestHubWinUI()` for testing within windows UI. It returns more clear errors and doesn't mention config file
- fix starting of stopped service
- rename windows shortcut in start menu
> improve win UI

- mem_windows.go
Instead of just '\Memory\Cache Bytes' perfcounter we should use the sum of:
-`\Memory\Standby Cache Normal Priority Bytes`
-`\memory\Standby Cache Reserve Bytes`
-`\Memory\Cache Bytes`
-`\Memory\Modified Page List Bytes`
> Fix cached memory on windows

- .circleci/config.yml
- Makefile
> Improve CI

- handler.go
- pkg/monitoring/vmstat/hyperv/provider_windows.go
- pkg/monitoring/vmstat/vmstat.go
- pkg/wmi/wmi.go
Check hyper-v feature is available inside `Acquire`
Query WMI feature with timeout
> fix: check vmstat is available inside Acquire

- cmd/cagent/winui.go
- config.go
WinUI save MinValuableConfig instead of full
> Save minconfig on windows

- pkg/hwinfo/hwinfo_windows.go
Fix case when returned baseboard slice is empty.
Do not fail on error and try to collect as much information as possible
> fix: improve error handling in hwinfo for windows

- pkg/monitoring/top/top.go
- Actually, the analysis could not be run more than one time per cagent' process lifetime
- The old data was never cleared
- If the process dies, now it will be deleted from the list, so the top will always contain fresh data
- some code simplified
> Address issues with stale data in the list of top-consuming processes

- pkg/monitoring/top/top.go
- pkg/monitoring/top/top_nonwindows.go
- pkg/monitoring/top/top_windows.go
- New field added: parent_pid
- Improvements to error handling for non-windows implementation
- Processes are grouped by key (parent_pid, process_name, command_line).
> Group top CPU-consuming processes

- processes.go
All similar methods use debug level and it looks more suitable
> Change log level to debug for ProcessesResult function

- pkg/winapi/facade.go
> Add additional sanity checks when reading external process memory

- build-mingw.sh
- pkg-scripts/msi-templates/product.wxs
Also add build script for MinGW64 environments.
> Resolve "error LGHT0204 : ICE64"

- cagent.go
- cmd/cagent/main.go
- cmd/cagent/winui.go
- config_test.go
- handler.go
* Refactor error representations (added pkg/wrap, proper logrus fields);
* Refactor winui hub config interaction.
This PR targets better error handling in cagent, also adds more control for timeouts and error cascading.
> Refactor error representations, plus winui hub config refactorings.

- handler.go
- pkg/hwinfo/hwinfo_nonwindows.go
- pkg/hwinfo/hwinfo_windows.go
display.list -> displays.list
listeningport.list -> listeningports.list
> Rename JSON field names for consistency

- handler.go
- pkg/monitoring/sensors/temperature.go
- pkg/monitoring/sensors/temperature_fallback.go
- pkg/monitoring/sensors/temperature_linux.go
- pkg/monitoring/sensors/temperature_windows.go
> Report temperature sensor values

- .circleci/config.yml
- Makefile
Some refactoring of the CircleCI workflows and aptly integration for non-rc builds
> Add aptly integration

- pkg/monitoring/sensors/temperature.go
- pkg/monitoring/sensors/temperature_linux.go
- pkg/monitoring/sensors/temperature_windows.go
> Rename result field for temperature sensor

- pkg/hwinfo/hwinfo_nonwindows.go
dmidecode can't read /dev/mem in some linux-systems (depending on kernel configuration options)
> Try catch dmidecode error accessing /dev/mem

- pkg/monitoring/sensors/temperature_windows.go
The first parameter should be hostname/IP
> Fix incorrect WMI (WBEM) server connection args

- .goreleaser.yml
Add package dependencies and update contact info
> Deb and fpm fixes

- .goreleaser.yml
- README.md
- SMART.md
- cagent.go
- config.go
- handler.go
- pkg-scripts/cagent-smartctl
- pkg/smart/check_required_tools_darwin.go
- pkg/smart/check_required_tools_linux.go
- pkg/smart/check_required_tools_windows.go
- pkg/smart/detect_disks_darwin.go
- pkg/smart/detect_disks_nix.go
- pkg/smart/detect_disks_windows.go
- pkg/smart/parse.go
- pkg/smart/parse_disk.go
- pkg/smart/parse_disk_test.go
- pkg/smart/smartctl_prepare_notwindows.go
- pkg/smart/smartctl_prepare_windows.go
- pkg/smart/smartctl_version_test.go
- pkg/smart/types.go
Parse and decode output provided by smartctl
- include prebuilt binary of `smartctl` for windows
> feat: S.M.A.R.T control

- pkg/monitoring/sensors/temperature_linux.go
Negative values from nouveau are errors. The sensor will be skipped.
see DEV-1022 for more details
> Add support for negative values from Nvidia GPU

- config.go
- handler.go
Add config option to pretty print hub measurements to file
Useful for debug purpose
> feat: add option to pretty print hub measurements to file

- cagent.go
- config.go
- handler.go
- pkg/smart/check_required_tools_darwin.go
- pkg/smart/check_required_tools_linux.go
- pkg/smart/check_required_tools_windows.go
- pkg/smart/detect_disks_darwin.go
- pkg/smart/detect_disks_nix.go
- pkg/smart/detect_disks_windows.go
- pkg/smart/options.go
- pkg/smart/parse.go
- pkg/smart/smart.go
- pkg/smart/smartctl_prepare_notwindows.go
- pkg/smart/smartctl_prepare_windows.go
- pkg/smart/smartctl_version_test.go
- pkg/smart/types.go
Add config param with smartctl executable
Detect location of smartctl
Fix smartctl execution on Win
> fix: detect smartctl executable

- pkg/osinfo/osinfo.go
- pkg/osinfo/osinfo_linux.go
- pkg/osinfo/osinfo_others.go
- pkg/osinfo/osinfo_windows.go
- system.go
report OS name and version on Linux targets
> feat: report full os version

- config.go
- example.config.toml
- handler.go
DEV-1114
```
temperature_monitoring = true # default true
```
> Add config entry to control temperature monitoring

- Gopkg.lock
- cmd/cagent/main.go
- pkg-scripts/postinstall-rpm.sh
- pkg-scripts/postinstall.sh
- vendor/github.com/kardianos/service/service_systemd_linux.go
- kardianos/service fork bug has been fixed
- fixed upgrading from old versions
***ported from frontman/pull/91***
> Refine service management during package update

- cmd/cagent/main.go
- config.go
- config_test.go
- example.config.toml
- handler.go
DEV-1116
New config variable is `heartbeat` (default 15).
Added validation for min interval values specified in config.
> Add the heartbeat: send GET request to HUB_URL every X seconds

- .circleci/config.yml
- .goreleaser.yml
- Makefile
- cagent.go
- cmd/cagent/main.go
- pkg/hwinfolib/hwinfolib_windows.go
- pkg/monitoring/sensors/temperature.go
- pkg/monitoring/sensors/temperature_fallback.go
- pkg/monitoring/sensors/temperature_linux.go
- pkg/monitoring/sensors/temperature_windows.go
Some more info here: DEV-1023
Changes include #170
> Updates in CI routine to support of proprietary MSI build

- cagent.go
- cmd/cagent/main.go
- pkg/hwinfolib/hwinfolib_windows.go
- pkg/monitoring/sensors/temperature.go
- pkg/monitoring/sensors/temperature_fallback.go
- pkg/monitoring/sensors/temperature_linux.go
- pkg/monitoring/sensors/temperature_windows.go
> Add support for HWiNFO lib to retrieve temperature sensor values

- config.go
- config_test.go
- example.config.toml
> Exclude virtual network interface by default

- cmd/cagent/main.go
- config.go
- example.config.toml
- handler.go
- pkg/common/common.go
> Add support for three operation modes: full, minimal and heartbeat

- config.go
- example.config.toml
To clarify that it applies only to io_mode=http
> Improve operation_mode config comment

- pkg/monitoring/services/services_nonwindows.go
> Add support for OpenRC init system support, allowing to list services on Alpine Linux

- example.config.toml
> Add all possible values of fs_metric config variable to example config

- Makefile
The scripts were slightly updated during frontman deployment task: DEV-1174
> Update repo deployment script according to new naming

- config.go
> Make inodes_used_percent metric enabled by default

- pkg/common/common.go
- pkg/hwinfo/hwinfo_nonwindows.go
- pkg/hwinfo/hwinfo_other.go
- pkg/monitoring/services/services_nonwindows.go
> Log missing dependencies only once

- pkg-scripts/msi-templates/product.wxs
> Add config to restart Windows service automatically on failure

- handler.go
> Fix panic caused by nil-pointer access. Error messages clarified

- config.go
- example.config.toml
- handler.go
> Add config field to control max HUB request time

- config.go
> Update hub_request_timeout default value

- Makefile
> Improve makefile syntax

- config.go
- example.config.toml
- pkg/monitoring/networking/watcher.go
> Add 'total' metric fields to sum up across network interfaces

- modules.go
> Report alerts and warnings list even if it was empty or nil slice

- config.go
- example.config.toml
- fs.go
- pkg/common/common.go
- pkg/monitoring/fs/fs_linux.go
- pkg/monitoring/fs/fs_others.go
- pkg/monitoring/fs/fs_windows.go
- pkg/monitoring/fs/watcher.go
- pkg/monitoring/sensors/temperature_linux.go
- processes_notwindows.go
> Add config field to filter out the FS mountpoints by device ID (enabled by default)

- cmd/csender/main.go
- pkg-scripts/msi-templates/product.wxs
- synology-spk/create_spk.sh
- wix.json
- fix service on windows (cagent.exe should be the first binary in wix.json)
- add help message for csender
- add cagent folder to PATH during the installation on Windows
> Csender help and win fixes

- pkg/monitoring/top/top_windows.go
- pkg/winapi/facade.go
- pkg/winapi/ntdll.go
- pkg/winapi/types.go
- pkg/winapi/user32dll.go
- pkg/winapi/winapi.go
- processes_windows.go
DEV-1338
- extract threads for each process to detect "suspended" processes
- query all windows with user32.dll to detect "not responding"(hanging) processes
> Detect win proc states: suspended and not responding

- cmd/jobmon/main.go
- config.go
- pkg-scripts/postinstall-rpm.sh
- pkg-scripts/postinstall.sh
- log output format updated to be similar to csender
- usage help text more user friendly
- fixed a problem when upgrading old cagent package: always invoke setting folder rights
DEV-1324
> Improvements to jobmon implementation

- config.go
- example.config.toml
- modules.go
- pkg/monitoring/raid/raid.go
> Allow to switch software RAID monitoring using config option 'software_raid_monitoring'

- .goreleaser.yml
- cagent.go
- config.go
- example.config.toml
- handler.go
- pkg-scripts/cagent-apt-get
- pkg-scripts/cagent-dnf
- pkg-scripts/cagent-yum
- pkg/monitoring/updates/apt.go
- pkg/monitoring/updates/pkgmgr.go
- pkg/monitoring/updates/updates.go
- pkg/monitoring/updates/updates_test.go
- pkg/monitoring/updates/yum.go
apt-get, yum and dnf are supported
DEV-1333
> Add monitoring of available updates

- config.go
- example.config.toml
- handler.go
- pkg/monitoring/processes/processes.go
- pkg/monitoring/processes/processes_notwindows.go
- pkg/monitoring/processes/processes_windows.go
- ports.go
DEV-1387
Also made a small refactoring:  process monitoring related code moved to separate package.
> Add configuration options for process monitoring to allow filtering and limits

- pkg/monitoring/updates/updates.go
DEV-1333
Only debian-based systems are supported.
> Add monitoring of 'reboot-required' system flag

- config.go
- example.config.toml
- handler.go
- pkg/monitoring/updates/updates.go
- pkg/monitoring/updates/watcher_windows.go
- pkg/proxydetect/proxydetect_windows.go
- set the check interval minimum to 300
- don't allow to run more than 1 query at once
> win updates: set the min interval

- cmd/cagent/main.go
Print to stdout instead of logger
> fix config test(-t)

- pkg/monitoring/sensors/temperature_windows.go
Old check was testing for English substring which resulted in excess error logs on non-English systems.
New check tests for returned error code.
> Make error logging condition to respect windows localization

- pkg/jobmon/writer.go
- pkg/jobmon/writer_test.go
> Fix the error working with slice. Tests added

- .circleci/config.yml
The orb implementation was added to separate repo: https://github.com/cloudradar-monitoring/circleci-orbs
> Add MS Teams build notifications

- config.go
- pkg/monitoring/updates/updates.go
DEV-1504
Fixes a problem of too short interval for checking system updates on 32-bit systems
> Fix system_updates_checks interval fields type usage

- config.go
- example.config.toml
- handler.go
- pkg/common/common.go
- pkg/monitoring/docker/docker_notwindows.go
- pkg/monitoring/updates/apt.go
- pkg/monitoring/updates/yum.go
Also added some minor refactoring to reuse the new code.
Fixes DEV-1508
> Add config fields to allow disabling docker monitoring and timeouts when executing docker commands

- pkg/monitoring/processes/processes_notwindows.go
- pkg/monitoring/processes/processes_notwindows_test.go
- Added some test
- Errors replaced with warning
> Rework /proc/<pid>/stat file parsing to catch more edge-cases

- handler.go
For all errors 400-599 - except 429 - wait until the next data submission is due according to the settings.
For 429 wait 10 seconds and try again
DEV-1601
> proper handling of submission interval

- config.go
- handler.go
> Turn on and off sub-parts

- pkg/monitoring/raid/mdstat_parser.go
- pkg/monitoring/raid/mdstat_parser_test.go
> raid: handle parsing of 'inactive' state, add tests

- config.go
- handler.go
- hub.go
Implements retry and give-up on hub Run() and RunHeartbeat() using a config like
```
on_http_5xx_retries = 4
on_http_5xx_retry_interval = 2.0
```
DEV-1668
> retries on http 5xx

- handler.go
> Adjust some error text and avoid some useless writes to log

- .circleci/config.yml
- .circleci/publish-packages.sh
- handler.go
> rework Run & RunHeartbeat retries to work correctly according to configured delays

- pkg/jobmon/spool.go
> jobmon: retry to acquire lock + add job id in errors

- pkg/jobmon/spool.go
> Improve jobmon spool multitasking

- config.go
- go.mod
- go.sum
- handler.go
- hub.go
> api friendly HTTP 401 error handling
