cloudradar-monitoring/cagent

- .circleci/config.yml
Tags like `1.0.0` will create a release as usual.
Tags like `1.0.0-rc1` and similar will create a pre-release
> Add a hack to be able to release pre-releases

- raid.go
- raid_test.go
**See DEV-369**
I made some changes.
Instead of `"raid.md0.array.state":"degraded"` I want to output `"raid.md0.degraded": "1"`
Because:
- Clean state is useless info(means there were no pending writes when the array was shut down)
- As I told before this states are only returned by mdadm, not mdstat
- Mdadm can return multiple states.
Here is an example of output...
Mdstat:
```
Personalities : [raid6] [raid5] [raid4]
md0 : active raid5 sda1[0] sdd1[2] sdb1[1]
1465151808 blocks level 5, 64k chunk, algorithm 2 [4/3] [UUU_]
unused devices: <none>
```
Output:
```
{
"md0.degraded": 1,
"md0.physicaldevice.missing": 1,
"md0.physicaldevice.state.sda1": "active",
"md0.physicaldevice.state.sdb1": "active",
"md0.physicaldevice.state.sdd1": "active",
"md0.state": "active",
"md0.type": "raid5"
}
``` …
> Raid output changed

- .circleci/config.yml
To be sure that build works on all platforms we run `goreleaser --snapshot` on every commit
> execute goreleaser —snapshot on every commit

- mem.go
- mem_windows.go
- types.go
See DEV-366.
I also improved the `available` memory metric.
- On Linux/Windows it uses the value provided by OS 
- On some OS(OpenBSD, Freebsd, Darwin) it calculated it as `free+cached+buffered` by [gopsutil]( https://github.com/shirou/gopsutil/blob/master/mem)
- Otherwise available metric must be nil
> Memory: calculate percentage and available memory on some systems

- build-win.bat
MSI only supports semver (e.g. 1.0.1.2)
In order to provide a clear upgrade flow for MSI, I made some updates to the bat to normalise the version like this:
1.0.2-rc1 -> 1.0.2.0.1
1.0.2-rc2 -> 1.0.2.0.2
1.0.2 -> 1.0.2.1
**Important note: This will provide incorrect version for input version without the patch part, e.g.`1.0`**
This doesn't affects version in the binary itself. Only for the MSI package
> Normalise versions with rc suffix

- cpu.go
On windows, perCPU measurements returned as Percentage, not CPU time
see https://github.com/shirou/gopsutil/issues/600
- Made a new calculation for windows (using percent not time)
- Filtered out outdated measurements (in case there was some timeouts)
- Added some comments to make the code more clear
> [CPU][Windows] fix util measurements

- .circleci/config.yml
This fixes the detection if a tag is an official release or a rc release
> Fix regex to properly detect rc versions by tag

- cmd/cagent/main.go
- config.go
Change the default log level `error` and print a warning if the user has set the log level to something we don't expect.
> Set default log level to error

- processes_windows.go
`ParentProcessId` was missing from the query fields
> Fix Parent PID on Windows

- cmd/cagent/main.go
While working on https://github.com/cloudradar-monitoring/cagent/pull/25 I noticed that I actually forgot to set the log level to default when the user provided an invalid value.
Only the warning was printed but that's it.
> set to default log level is the user has provded an invalid value

- cmd/cagent/main.go
- handler.go
- pkg-scripts/postinstall.sh
See DEV-486
We need a way to test the HUB connection & creds.
This will be run as a postscript in pkg installers in order to provide fast feedback for the user. 
It can be useful when a user has firewall blocking outgoing connection or made a typo in the credentials
> -t flag to test the HUB connection & creds

- network.go
- types.go
Split big Results() method
gocyclo:
```
12 cagent (*netWatcher).fillCountersMeasurements network.go:136:1
12 cagent (*netWatcher).ExcludedInterfacesByNameMap network.go:88:1
10 cagent IPAddresses network.go:220:1
```
> Refactor network.go

- cmd/cagent/main.go
- config.go
- cpu.go
- fs.go
- handler.go
- network.go
- windows.go
- windows_fallback.go
- Split Run() method into (Run, RunOnce, GetAllMeasurements, ReportMeasurements)
- Move watchers into the Cagent struct
gocyclo before:
```
32 cagent (*Cagent).Run handler.go:135:1
11 cagent (*Cagent).TestHub handler.go:54:1
8 cagent (*Cagent).PostResultsToHub handler.go:86:1
7 cagent (*Cagent).initHubHttpClient handler.go:22:1
```
after: 
```
14 cagent (*Cagent).GetAllMeasurements handler.go:133:1
11 cagent (*Cagent).TestHub handler.go:52:1
8 cagent (*Cagent).PostResultsToHub handler.go:84:1
7 cagent (*Cagent).initHubHttpClient handler.go:20:1
5 cagent (*Cagent).Run handler.go:259:1
```
Todo: 
- Move different watchers into /pkg/monitoring
- Create an interface(New, Results)
- Make the code less repetitive (init watcher, get measurements, fill results map with a prefix)
But I think it is …
> refactor handler.go

- cmd/cagent/main.go
- handler.go
after refactoring, file output mode was partly broken
- in run-once mode file was closed before output
- results was still pushed to the HUB even file output mode is active
> fix file output mode

- processes_notwindows.go
improve both `/proc/<pid>` and ps methods.
Because our goal is to create the tool for a wide range of systems we should try to avoid relating to unclear structures
What changed in this PR:
- in the case of `ps` method parse the header to make sure ps returns requested fields(and in the right order)
- in case of `/proc/<pid>` method switch from `/proc/<pid>/stat` to the `/proc/<pid>/status` parsing. According to some sources `ppid` is 3rd, other shows it 4th so it may differ from system to system. Also, it turned out that 2nd param(executable name) can contain spaces and breaks the parsing
This should theoretically solve DEV-654 and other similar issues
> Fix processes info parsing

- handler.go
- pkg/hwinfo/hwinfo.go
- pkg/hwinfo/hwinfo_nonwindows.go
Report `cagent.success: 1` if `dmidecode` tool is not present if the system
> fix: do not fail if dmidecode is not present

- cmd/cagent/main.go
- do not exit if hub_url is not set. Instead, show the steps to fix this
- fix log path(was config path instead)
This allows `dpkg -i` to install cagent service without credentials and put them later
> remove service install hub_url fatal error

- handler.go
- pkg/monitoring/docker/docker.go
- pkg/monitoring/docker/docker_common.go
- pkg/monitoring/docker/docker_windows.go
- processes_notwindows.go
- Currently, it tries to connect to the Unix socket on windows, producing errors
- It is still possible to use it on windows via a named pipe, but @thorstenkramm said that we should disable docker on Windows as this is is a pretty rare case.
- As advantage, this saves some binary size on Windows :)
> Disable docker on windows

- config.go
- example.config.toml
- handler.go
- pkg/monitoring/services/services.go
- pkg/monitoring/services/services_windows.go
To fulfill DEV-585 discussion.
- detect auto_start(*see notes below)
- show only autostarting service by default(discover_autostarting_services_only in config)
- use `state` field for all of system managers to make filtering in the UI easier
- query `delayed autostart` status on win
- make win values lowercase 
*auto_start detection
- On Windows they have the `run=auto`
- On Linux SystemD I'm filtering only __STATE=enabled__ services from `systemctl --type=service --all --no-pager --plain --output=json list-unit-files`
- TODO: SysVinit/upstart currently assuming all services as auto-start. Will need to solve this by parsing unit files or list&correlate symlinks from `/etc/rc*.d`
> Improve services list

- pkg/monitoring/top/top_nonwindows.go
Fix for #71 
Ignore the processes completely in case something goes wrong. Likely for short-lived processes
> ignore failed processes, if we log the errors we get way too many errors

- cmd/cagent/main.go
- handler.go
- Fix typo (succeed->succeeded)
- Show instruction on how to restart the service only in case there is an error and service is actually installed
- Improve the pkg installer output
> Deb/rpm and -t fixes

- processes.go
As we talked in Slack, all results keys should be lowercase.
Need an additional check on the side of the backend(HUB). May probably need a migration for the existence checks created by users in the DB @thorstenkramm
> make proc.* keys lowercase

- cagent.go
- handler.go
- pkg/monitoring/docker/docker.go
- pkg/monitoring/docker/docker_windows.go
- processes.go
- processes_notwindows.go
- processes_windows.go
The check I have before was not enough, because for some cases docker lib returns the different error.
So the new plan is:
- check if executable `docker` is presented at `$PATH`. 
- If `docker` is not presented on system AND docker request wasn't successful within the session we can omit the error
> improve docker missing error handling

- cmd/cagent/main.go
- log.go
Make the auto-created log dir(`/var/log/cagent` on Linux) `777` perms and the log file itself `666`.
It will allow the case when the user removed the log file manually inside the dir that was created during the installation with `sudo` and then run `cagent` under unprivileged user
> Fix log dir/file perms

- cpu.go
- processes_windows.go
- types.go
- do not stop the CPU watcher if 1st query returns timeout
- change `cpuGetUtilisationTimeout` and `measureInterval` for 20 seconds
- return better human-readable error instead of `context deadline exceeded` for WMI queries in CPU and win processes list
> Improve WMI timeouts handling

- Gopkg.lock
- Gopkg.toml
- pkg/hwinfo/hwinfo_nonwindows.go
- vendor/github.com/cloudradar-monitoring/dmidecode/dmidecode.go
- vendor/github.com/cloudradar-monitoring/dmidecode/types.go
Some important DMI types like Base Board may be absent.
To fix continues inventory running even required fields are missing to gather as much information as possible
> fix: hwinventory do not fail if DMI type not found

- README.md
after parameter -o must be filename
add $GOPATH in parameter git-dir for using relative path
> fix instruction for build from sources

- pkg/monitoring/vmstat/hyperv/hyperv_wmi.go
@thorstenkramm reported a panic ...
seems the variable name was wrong
> Fix var name

- cpu.go
Fixing faulty values for CPU utilization:
```
"cpu.util.idle.1.cpu0": -92233720368547760,
"cpu.util.idle.1.cpu1": -92233720368547760,
"cpu.util.user.1.cpu0": -92233720368547760,
"cpu.util.user.1.cpu1": -92233720368547760,
"cpu.util.idle.1.total": -92233720368547760,
"cpu.util.user.1.total": -92233720368547760,
"cpu.util.system.1.cpu0": -92233720368547760,
"cpu.util.system.1.cpu1": -92233720368547760,
"cpu.util.system.1.total": -92233720368547760,
```
It seems that when throttling CPU (using cpuburn for example), cagent get WMI query timeouts. This causes time series for cpu.util metrics for last time interval (d) to become empty (tsa.TimeSeries)
> Fix division by zero

- pkg/hwinfo/hwinfo_windows.go
- pkg/monitoring/services/services_windows.go
- processes_windows.go
When doing WMI queries some fields may be missing on some systems. WMI returns nil for them, but the `github.com/StackExchange/wmi` lib we are using is failing to set the struct field because it is not a pointer but just the value and we got all the query failed even if it just 1/999 process which has a nil value. So...
- Let's make all the fields pointers
- Check for nil if we need to make some operations on the value
Also, I made some optimization in hwinfo. I have commented out all the unused fields so the WMI query could become faster and less memory consuming
> Fix nil WMI fields

- cagent.go
- handler.go
- pkg/monitoring/vmstat/hyperv/provider_windows.go
- pkg/monitoring/vmstat/types/types.go
- pkg/monitoring/vmstat/vmstat.go
package name for pkg/monitoring/vmstat/types/types.go was non-conforming to Go guidelines, forcing us to specify the package name explicitly to pass GolangCI checks.
> Fix package naming according to Go guidelines

- raid.go
It was printing error message, but actually this is not an error.
> Change severity level of log message when RAID stats is not available

- pkg-scripts/msi-templates/product.wxs
When upgrading from 1.0.0 or 1.0.3 to newer packages (1.0.4 and higher), the user can get two installations in the list of installed programs.
The reason is that in 1.0.4 we changed the installation scope to 'per Machine'.
I've read tons of documentation/mail groups and it looks like this problem is really old. The official recommendation from MS is to never change the installation scope (perUser  -> perMachine).
This PR will stop installation if old versions were detected.
The detection based on the registry keys search. It seems to be the only reliable way to distinguish between versions.
Upon detection, the message "The old cagent installation which cannot be upgraded was found. Please remove it and restart the installer." will be shown and the installer will exit.
Also, the …
> Stop installation if the old version of cagent (installed in per-user scope) was detected

- pkg/winapi/facade.go
- pkg/winapi/types.go
- pkg/winapi/winapi.go
- processes_windows.go
WMI query is slow and actually does not work when the system is under high load.
1) This PR replaces WMI query with winapi calls, which are:
- list all the processes in system using one winapi call
- for each process tries to get its command line string. (3-4 winapi calls). 
2) Also, some refactorings made to simplify winapi module.
***
Note that in some cases we are unable to get the command line string at all:
- for some system processes, which memory is inaccessible in user mode
- when running 32-bit cagent under WOW64, only 32-bit processes memory is accessible for cagent.
***
Tested on Win10, Windows Server (2012, 2016, 2019)
> Eliminate wmi query for process list

- handler.go
- ports.go
- processes.go
Cagent now will return a list of local open TCP ports similar to the output of "netstat -tulpen" on Linux.
An object  `"listeningport.list": []" is appended to the result object.
> List open ports

- system.go
- system_notwindows.go
- system_windows.go
Now it will use value from registry.
> Eliminate WMI call for CPU name retrieval on Windows

- pkg/common/errors.go
- pkg/hwinfo/hwinfo.go
- pkg/hwinfo/hwinfo_darwin.go
- pkg/hwinfo/hwinfo_nonwindows.go
- pkg/hwinfo/hwinfo_other.go
- pkg/hwinfo/hwinfo_windows.go
- pkg/hwinfo/system_profiler.go
- pkg/hwinfo/system_profiler_test.go
There was a problem of mixing real errors and minor info messages together.
This PR changes all work with errors to be consistent with the rest part of cagent.
> Rework hwinfo package error handling

- .gitignore
- .goreleaser.yml
- cmd/cagent/main.go
- pkg-scripts/postinstall.sh
- pkg-scripts/preremove-rpm.sh
- Added -y option (automatic yes to prompts). This option should be used when no interaction with user is required (e.g. during package installation)
- special version of preremove script is added for RPM packaging. It can distinguish between upgrade and casual uninstall routine.
- 'dist' folder added to .gitignore
- fixed console output when asking confirmation.
> Fix RPM package upgrade routine

- handler.go
- mem.go
- mem_windows.go
- pkg/common/common.go
- pkg/monitoring/top/top_windows.go
- pkg/winapi/facade.go
- processes.go
- processes_notwindows.go
- processes_windows.go
New fields added for each process:
```
cpu_avg_usage_percent
rss // Resident Set Size or Private Working Set Size (actual memory size used by process)
vms // Virtual Memory Size (for some systems like Windows it's very big by default, even if process does not use it)
memory_usage_percent
```
The cpu_avg_usage_percent calculated since last check, therefore it's available only after second check.
> Monitor memory and CPU used by each process

- pkg/hwinfo/hwinfo_other.go
If some system file is missing, it's not an error. We will report it as 'info' message
> Do not fail if there was any stderr output from ghw/pci library

- pkg/monitoring/services/services_nonwindows.go
While testing on the Synology devices I experienced a panic on startup.
The earlier check:
```go
if strings.HasPrefix(parts[0], "network-interface") {
continue
}
```
is not enough because other, unexpected, values can appear.
I added a more generic check and in case of an unexpected outcome the value is logged and the entry ignored.
> Fix potential panic when listing upstart services

- pkg/hwinfo/hwinfo_darwin.go
- pkg/hwinfo/hwinfo_nonwindows.go
- pkg/hwinfo/hwinfo_other.go
on MacOS it provides result without being called as sudo
Call with sudo prompts for password and it fails due to
absence of `cagent-dmidecode` for MacOS package
> fix: run dmidecode without sudo on Darwin

- pkg/monitoring/docker/docker.go
As reported by a customer the `docker inspect` command was called without the containers id.
Added the `id` to the executed command
> Pass container id to docker inspect

- pkg/hwinfo/hwinfo_other.go
`ghwErr` check for `non-nil` is always false due to shadowing in lambda
> fix: error shadowing

- .goreleaser.yml
`smartmontools` in most linux distributions is of version `6.5` comparing to required by cagent `7.0`
> fix: remove dependency to smartmontools

- pkg/common/common.go
- pkg/hwinfo/hwinfo_darwin.go
- pkg/hwinfo/hwinfo_nonwindows.go
- pkg/hwinfo/hwinfo_other.go
On *nix and darwin use `/proc/cpuinfo` and `sysctl` respectively to detect CPU information.
Fixes issue when OS is running on `VmWare` and `dmidecode` reports amount of sockets provided by hypervisor.
> fix: detect CPU count on *nix and darwin

- cmd/cagent/main.go
- handler.go
- log.go
- network.go
- pkg/common/errors.go
- raid.go
- raid_test.go
- system.go
All warnings fixed:
```
$ golangci-lint run  -c .golangci.yml --skip-dirs vendor/
raid.go:48:44: parseMdstat - result 1 (error) is always nil (unparam)
func parseMdstat(data string) (RaidArrays, error) {
^
handler.go:187:1: cyclomatic complexity 29 of func `(*Cagent).GetAllMeasurements` is high (> 25) (gocyclo)
func (ca *Cagent) GetAllMeasurements() (common.MeasurementsMap, error) {
^
system.go:21:2: `unameTimeout` is unused (deadcode)
unameTimeout    = 5 * time.Second
^
cmd/cagent/main.go:561:21: Error return value of `cmd.Process.Release` is not checked (errcheck)
cmd.Process.Release()
^
log.go:73:15: SA4006: this value of `err` is never used (staticcheck)
plainformat, err := hook.formatter.Format(entry)
^
raid.go:25:14: S1007: should use raw string (`...`) with regexp.MustCompile to …
```
> Fix warnings reported by go vet and golangci-lint

- .circleci/config.yml
- Makefile
- synology-spk/create_spk.sh
Turns out circleci produced shared binaries which did not work in Synology DSM.
Using CGO_ENABLED=0 we force the binary to be statically linked.
Also update gobuild and some circleci tweaks
Follow-up to DEV-1117
Corresponding frontman pr: https://github.com/cloudradar-monitoring/frontman/pull/99/
> spk: force build static binaries

- .circleci/config.yml
A new key pair was created.
The old key wasn't added to authorized keys on the repos' host
> Update package repo server SSH keys

- cmd/cagent/main.go
- handler.go
There was an error because of reading from an empty channel.
It resulted in hunging package uninstallation (service could not be stopped)
> Fix go routine lock after sending kill signal

- config.go
- config_test.go
- example.config.toml
- network.go
- pkg/monitoring/networking/net_notwindows.go
- pkg/monitoring/networking/net_windows.go
- pkg/monitoring/networking/watcher.go
- pkg/winapi/iphlpapi.go
- pkg/winapi/win_386.go
- pkg/winapi/win_amd64.go
DEV-1039.
1) Update 'bytes per second' calculation for windows.
The old implementation could return incorrect value due to errors in underlying library (gopsutil).
2) Add config field to set fixed value for max network link speed.
> Update 'bytes per second' calculation for windows.

- mem_windows.go
- perfcounters/pdh.go
- pkg/hwinfo/hwinfo_windows.go
- pkg/monitoring/docker/docker_windows.go
- pkg/monitoring/services/services_windows.go
- pkg/monitoring/top/top_windows.go
- pkg/winapi/ntdll.go
- pkg/winapi/types.go
- processes_windows.go
- windows.go
(use GOOS=windows to execute it on windows code).
Not all warnings fixed.
> Fix minor golangci-lint warnings for windows code

- cmd/cagent/main.go
- pkg-scripts/msi-templates/product.wxs
Shown in "Services" on Windows and in the output of "service cagent status" command on Linux systems.
> Add meaningful description of installed cagent service

- Makefile
Debian policy does not allow adding packages with the same (name, arch, version) into one repository.
armv6 and armv7 produce the same architecture 'armhf' which causes the aptly to add only one package to the repo and spit out a warning.
DEV-1076
> Exclude armv6 deb package from Aptly repo

- .goreleaser.yml
- pkg-scripts/cagent-dmidecode
- pkg/hwinfo/hwinfo_nonwindows.go
- pkg/monitoring/services/services_nonwindows.go
Also:
- add dbus to the list of recommended packages: DEV-1177
- fix dmidecode detection. Now info message will be logged instead of an error
> Update package build to recommend dependant tools instead of hard requirement

- config.go
- config_test.go
There was an error when the log level wasn't set at all, causing cagent to use `info` instead of `error`
> Set default log level explicitly

- pkg/hwinfo/hwinfo_darwin.go
- pkg/hwinfo/hwinfo_other.go
- pkg/hwinfo/hwinfo_windows.go
- pkg/hwinfo/wmi_types.go
It was working properly only for Windows 10 and above.
Windows Server 2008 was crashing here due to implementation.
Other systems reported incorrect values.
More details: DEV-1253
> Remove 'core_enabled' metric for CPU info

- pkg/monitoring/networking/net_linux.go
Some network cards can report "-1" link speed on linux. Old code ignored this leading to 0.0/0.0 -> NaN, which could not be serialized to JSON result object
> Fix error working with NaN value

- config.go
- example.config.toml
- pkg/monitoring/fs/fs_notwindows.go
- pkg/monitoring/fs/fs_windows.go
- pkg/monitoring/fs/watcher.go
The old Windows implementation was returning 'NTFS' for all network shared volumes.
The Linux implementation is left untouched.
DEV-1250
> Make FS monitoring to detect network volumes FS type on Windows

- config.go
- example.config.toml
- handler.go
- modules.go
- pkg/common/types.go
- pkg/monitoring/module.go
- pkg/monitoring/storcli/parser.go
- pkg/monitoring/storcli/parser_test.go
- pkg/monitoring/storcli/storcli.go
- pkg/monitoring/storcli/storcli_notwindows.go
- pkg/monitoring/storcli/storcli_windows.go
- new 'timestamp' field: the time of last check
- virtual drive names now extracted from info to improve error messages
- new fields added to report: VDs status and the number of physical drives
- modules system reworked to support multiple reports per module. The storcli command execution status is always added to result object
DEV-1247
> Improve storcli reporting

- build-win.bat
- synology-spk/create_spk.sh
embed the right csender binary in the synology (all archs) and win x86 releases
> fix wrong csender binary on synology&win_x86

- config.go
- handler.go
- hub.go
- smart.go
- vm.go
Main motivation is to reduce the upcoming Pull Request with jobmon feature (DEV-1324). 
I need to implement some new behavior in handler.go (to call some cleanup function if measurements were succefully reported to Hub or output file).
I decided to make some refactoring in this file as it is too big.
Main changes:
- Hub-related functions have been moved to hub.go. In future we can decouple it from Cagent object and reuse in other places (like csender, or even frontman).
- SMART and VMs monitoring measurements collection moved to separate files similar to other measurements
- Functions in handler.go slightly reordered and access mode updated (public->private).
- collectMeasurements function implementation slightly simplified
- one function moved from config.go to handler.go as this is the …
> Split large handler.go file

- Makefile
First one allows to run goreleaser of specified version via Docker (without publishing the release). It allows to check that all binaries compiled successfully before pushing changes to Git.
Second one allows to run golangci-lint (for the same reason).
> Add two handy Makefile scripts which can be useful during development

- hub.go
- pkg/csender/hub.go
- pkg/proxydetect/proxydetect.go
- pkg/proxydetect/proxydetect_nonwindows.go
- pkg/proxydetect/proxydetect_windows.go
- pkg/winapi/types.go
- pkg/winapi/winapi.go
- pkg/winapi/winhttp.go
Here is a list of priority when getting proxy on Windows(first non-error non-nil is chosen):
- hub_proxy from config
- HTTP_PROXY, HTTPS_PROXY and NO_PROXY (and lowercase variants) from env vars
- In case Autodetect is enabled in the Internet Options, use [Proxy Autodetect via DHCP and DNS_A](https://docs.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpdetectautoproxyconfigurl#parameters) to get the proxy, then apply the bypass list
- In case Automatic config URL is specified in the Internet Options use it to get the proxy, then apply the bypass list
- Use manual proxy if specified in the Internet Options, then apply the bypass list
- Use the default WinHTTP proxy configuration from the registry. [Usually set with …
> proxydetect package for windows system proxy detection

- config.go
- handler.go
- windows.go
DEV-1390
- add `windows_update` option to the config (`true` by default)
- disable windows update watcher if `windows_updates_watcher_interval`<=0
- pass system errors from windows update query to the measurements
- add a more clear user-facing error in case "Windows Updates" is disabled on the host
> add windows_update to config and provide more clear error

- pkg-scripts/cagent-dnf
- pkg-scripts/cagent-yum
- pkg/monitoring/updates/apt.go
- pkg/monitoring/updates/pkgmgr.go
- pkg/monitoring/updates/updates.go
- pkg/monitoring/updates/yum.go
DEV-1333
Debian-based systems will call apt-check if it's available. (Installed by default starting from Ubuntu 12).
CentOS will call yum security plugin if installed. (Installed by default starting from CentOS 7.)
Null field supplied in result object otherwise.
> Add the monitoring of 'security' updates where possible

- pkg/proxydetect/proxydetect_windows.go
According to this document, this is not a critical error
https://docs.microsoft.com/en-gb/archive/blogs/avkashchauhan/winhttpgetproxyforurl-failed-error_winhttp_autodetection_failed-12180-error-message-in-windows-azure-infrastructure-log
> win proxy discard error 12180

- pkg/monitoring/updates/updates.go
- pkg/monitoring/updates/watcher_windows.go
Instead of the Unix timestamp, it will be better to provide relative time in seconds.
`last_update_timestamp` -> `last_updates_installed_ago_sec`
Also added `last_query_age_sec`
> win updates: use relative time

- cmd/cagent/main.go
- config.go
- handler.go
- pkg-scripts/msi-templates/product.wxs
- pkg/monitoring/top/top.go
- pkg/monitoring/updates/updates.go
Add logging of runtime errors for two goroutines.
Enable Windows Update watcher by default.
Add logging of cagent service startup.
Update Windows service restart policy to "restart always"
> Add more error handling code for debug purposes and enable windows update watcher

- pkg/monitoring/processes/processes_windows.go
- pkg/winapi/user32dll.go
DEV-1429
syscall.NewCallback() may be called only 2000 times in Go runtime.
Afterwards it throws a panic. The implementation updated to execute it only once.
```
fatal error: too many callback functions
goroutine 11 [running]:
runtime.throw(0xab4c6e, 0x1b)
/usr/lib/go/src/runtime/panic.go:774 +0x79 fp=0xc00010f120 sp=0xc00010f0f0 pc=0x431209
syscall.compileCallback(0x9c2280, 0xc00050d690, 0x40db01, 0xa5b1e0)
/usr/lib/go/src/runtime/syscall_windows.go:89 +0x2db fp=0xc00010f160 sp=0xc00010f120 pc=0x44bb2b
syscall.NewCallback(...)
/usr/lib/go/src/syscall/syscall_windows.go:147
github.com/cloudradar-monitoring/cagent/pkg/winapi.WindowByProcessId(0xc0006deba0, 0x9e239f98f5c5, 0x1034360)
/home/nikita/go/src/github.com/cloudradar-monitoring/cagent/pkg/winapi/user32dll.go:45 +0x85 fp=0xc00010f198 …
```
> Fix panic "too many callbacks" when running agent for a long time on Windows

- handler_test.go
- pkg/hwinfo/hwinfo_other.go
Test coverage increased from 16% to 35%
```
➜ go tool cover  -func=cover.out | grep total          
total:                                       (statements)                     16.1%
➜ go tool cover  -func=cover_new.out | grep total      
total:                                       (statements)                35.3%
```
> Add "integration" test for cagent main function

- .circleci/config.yml
- .goreleaser.yml
- Makefile
goreleaser uses "git describe" command to get release name. It always returns same tag even if there are multiple tags pointing to same commit.
Starting from v0.126 goreleaser supports overriding tag name using env variable: https://github.com/goreleaser/goreleaser/pull/1327
> Fix building releases when multiple tags pointing to the same commit

- pkg/monitoring/processes/processes_notwindows.go
This PR fixes the case where the "proc.list" Measurement contains Inf or NaN values. This happens if cagent is configured with `mem_monitoring = false`
JSON marshal cannot encode Inf or NaN values and errors out trying to send to hub.
example input that cause the issue:
```
&processes.ProcStat{PID:17355, ParentPID:995, ProcessGID:979, Name:"sleep", Cmdline:"sleep 60", State:"sleeping", Container:"", CPUAverageUsagePercent:0, RSS:0xc9000, VMS:0x71c000, MemoryUsagePercent:+Inf},
&processes.ProcStat{PID:15071, ParentPID:2, ProcessGID:0, Name:"kworker/0:7-events", Cmdline:"", State:"idle", Container:"", CPUAverageUsagePercent:0, RSS:0x0, VMS:0x0, MemoryUsagePercent:NaN},
```
DEV-1581 follow-up
> fix json encode error when sending to hub

- pkg/monitoring/processes/processes_windows.go
Same as https://github.com/cloudradar-monitoring/cagent/pull/269 but for the Windows code path.
DEV-1581
> fix memUsagePercent calculation if cagent is configured with mem_monitoring = false for the windows path

- README.md
Previously the line stated that the logs go in to the configuration file on the Unix system. I suspect this is unlikely and a simple copy+paste error of the configuration section above.
This change updates the README to describe the true default destination of the logs.
> Log location for Unix is cagent.log

- Makefile
A small fix to use host machine GOCACHE folder correctly.
> Fix docker-goreleaser Makefile job to obtain env variable correctly

- pkg/csender/hub.go
Fixes for:
```
pkg/csender/hub.go:71:11: `if` block ends with a `return` statement, so drop this `else` and outdent its block (golint)
} else {
^
pkg/csender/hub.go:78:3: S1000: should use a simple channel send/receive instead of `select` with a single case (gosimple)
select {
^
```
> Simplify code according to golangci-lint warnings
